<robot name="mycar" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="footprint_radius" value="0.001" />
    <!--1.添加 base_footprint-->
    <link name="base_footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
        </visual>
    </link>

    <xacro:property name="base_radius" value="0.1" />  
    <xacro:property name="base_length" value="0.08" />
    <xacro:property name="base_mass" value="2" />
    <xacro:property name="base_lidijianju" value="0.015" />
    <xacro:property name="base_joint_z" value="${base_length/2+base_lidijianju}" />
    <!--2.添加底盘-->
    <!--底盘为圆柱状，半径 10cm，高 8cm.底盘离地间距为 1.5cm-->
    <!--2-1.link-->
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>

            <origin xyz="0 0 0" rpy="0 0 0" />

            <material name="baselink_color">
                <color rgba="1 0.5 0.2 0.5" />
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
        </collision>
        <!-- 调用惯性矩阵函数 -->
        <xacro:cylinder_inertial_matrix m="${base_mass}" r="${base_radius}" h="${base_length}" />
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/Yellow</material>
    </gazebo>
    <!--2-2.joint-->
    <joint name="link2footprint" type="fixed" >
        <parent link="base_footprint" />
        <child link="base_link" />
        <!--车高0.08/2+离地间距0.015-->
        <origin xyz="0 0 ${base_joint_z}" rpy="0 0 0" />
    </joint>

    <!-- 本质：相同的参数属性封装，不同的参数进行传参 -->
    <xacro:property name="wheel_radius" value="0.0325" />
    <xacro:property name="wheel_length" value="0.015" />
    <xacro:property name="wheel_mass" value="0.05" />
    <xacro:property name="PI" value="3.1415927" />
    <xacro:property name="wheel_joint_z" value="${wheel_radius-base_joint_z}" />
    <!-- 驱动轮 -->
    <xacro:macro name="wheel_func" params="wheel_name flag">

        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>

                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />

                <material name="${wheel_name}_wheel">
                    <color rgba="0 0 0 0.3" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="${PI/2} 0 0" />
            </collision>
            <xacro:cylinder_inertial_matrix m="${wheel_mass}" r="${wheel_radius}" h="${wheel_length}" />
        </link>
        <gazebo reference="${wheel_name}_wheel">
            <material>Gazebo/Red</material>
        </gazebo>
        <!--3-2.joint-->
        <joint name="${wheel_name}2link" type="continuous" >
            <parent link="base_link" />
            <child link="${wheel_name}_wheel" />
            <!--
                x 无偏移
                y 车体半径
                z 车轮半径0.0325-(车高0.08/2+离地间距0.015)
            -->
            <origin xyz="0 ${flag*0.1} ${wheel_joint_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>

    <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />

    <!--4.添加万向轮-->
    <!--
            形状: 球体
            半径: 0.75 cm
            颜色: 黑色
    -->
    <xacro:property name="small_wheel_radius" value="0.0075" />
    <xacro:property name="small_wheel_mass" value="0.01" />
    <xacro:property name="small_wheel_z" value="${small_wheel_radius-base_joint_z}" />  
    
    <xacro:macro name="small_wheel_func" params="small_wheel_name flag" >
        <!--4-1.link-->
        <link name="${small_wheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${small_wheel_radius}" />
                </geometry>

                <origin xyz="0 0 0" rpy="0 0 0" />

                <material name="${small_wheel_name}_wheel">
                    <color rgba="0 0 0 0.3" />
                </material>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${small_wheel_radius}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
            </collision>
            <xacro:sphere_inertial_matrix m="${small_wheel_mass}" r="${small_wheel_radius}" />
        </link>
        <gazebo reference="${small_wheel_name}_wheel">
            <material>Gazebo/Red</material>
        </gazebo>
        <!--4-2.joint-->
        <joint name="${small_wheel_name}2link" type="continuous" >
            <parent link="base_link" />
            <child link="${small_wheel_name}_wheel" />
            <!--
                x 万向轮是在车子下面放置的，取值为:（0，半径）
                y 0
                z 车轮半径0.0075-(车高0.08/2+离地间距0.015)
            -->
            <origin xyz="${flag*0.08} 0 ${small_wheel_z}" rpy="0 0 0" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>

    <xacro:small_wheel_func small_wheel_name="front" flag="1" />
    <xacro:small_wheel_func small_wheel_name="back" flag="-1" />

</robot>
