<robot name="mycar" xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="footprint_radius" value="0.001" />
    <link name="footprint">
        <visual>
            <geometry>
                <sphere radius="${footprint_radius}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="foot_color">
                <color rgba="0 0 1 1" />
            </material>
        </visual>
    </link>

    <xacro:property name="base_radius" value="0.15" />
    <xacro:property name="base_length" value="0.1" />
    <xacro:property name="lidi" value="0.02" />
    <xacro:property name="baselink_z" value="${base_length/2 + lidi}" />
    <link name="base_link">
        <visual>
            <geometry>
                <cylinder radius="${base_radius}" length="${base_length}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="base_color">
                <color rgba="0.5 0.5 0 0.5" />
            </material>
        </visual>
    </link>
    <joint name="foot2base" type="fixed">
        <parent link="footprint" />
        <child link="base_link" />
        <origin xyz="0 0 ${baselink_z}" rpy="0 0 0" />
    </joint>


    <xacro:property name="wheel_radius" value="0.04" />
    <xacro:property name="wheel_length" value="0.015" />
    <xacro:property name="wheel_joint_y" value="${base_radius + wheel_length/2}" />
    <xacro:property name="wheel_joint_z" value="${(base_length/2 + lidi - wheel_radius) * (-1)}" />
    
    <xacro:macro name="wheel_func" params="wheel_name flag">
        <link name="${wheel_name}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />
                </geometry>
                <origin xyz="0 0 0" rpy="1.5708 0 0" />
                <material name="wheel_color">
                    <color rgba="0 0 0 0.5" />
                </material>
            </visual>
        </link>
        <joint name="${wheel_name}2base" type="continuous">
            <parent link="base_link" />
            <child link="${wheel_name}_wheel" />
            <origin xyz="0 ${flag * wheel_joint_y} ${wheel_joint_z}" />
            <axis xyz="0 1 0" />
        </joint>
    </xacro:macro>
    <xacro:wheel_func wheel_name="left" flag="1" />
    <xacro:wheel_func wheel_name="right" flag="-1" />

    <xacro:property name="small_wheel_radius" value="0.01" />
    <xacro:property name="small_wheel_joint_x" value="${base_radius * 0.9}" />
    <xacro:property name="small_wheel_joint_z" value="${(base_length/2 + lidi - small_wheel_radius) * (-1)}" />
    <xacro:macro name="small_wheel_func" params="small_wheel_name flag" >
        <link name="${small_wheel_name}_wheel">
            <visual>
                <geometry>
                    <sphere radius="${small_wheel_radius}"  />
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <material name="wheel_color">
                    <color rgba="0 0 0 0.5" />
                </material>
            </visual>
        </link>
        <joint name="${small_wheel_name}2base" type="continuous">
            <parent link="base_link" />
            <child link="${small_wheel_name}_wheel" />
            <origin xyz="${flag * small_wheel_joint_x } 0 ${small_wheel_joint_z}" />
            <axis xyz="1 1 1" />
        </joint>
    </xacro:macro>
    <xacro:small_wheel_func small_wheel_name="front" flag="1" />
    <xacro:small_wheel_func small_wheel_name="back" flag="-1" />

</robot>