<robot name="" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- 1.属性定义 -->
    <xacro:property name="PI" value="3.14159" />
    <xacro:property name="radius" value="10" />
    <!-- 2.属性调用 -->
    <myUserPropertyxx name="${PI}" />
    <myUserPropertyxx name="${radius}" />
    <!-- 3.算术运算 -->
    <myUserPropertyYY name="${radius * 2}" />
    <myUserPropertyYY name="${PI / 2}" />

</robot>