<robot name="mycar" xmlns:xacro="http://www.ros.org/wiki/xacro">


    <xacro:property name="support_radius" value="0.035" />
    <xacro:property name="support_length" value="0.3" />
    <xacro:property name="laser_raius" value="0.08" />
    <xacro:property name="laser_length" value="0.08" />

    <xacro:property name="support_joint_z" value="${base_length/2 + support_length/2}" />
    <xacro:property name="laser_joint_z" value="${support_length/2 + laser_length/2 }" />

    <link name="support">
        <visual>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_length}" />
            </geometry>
            <material name="support_color">
                <color rgba="0 0 0 0.8" />
            </material>
        </visual>
    </link>
    <joint name="base2support" type="fixed">
        <parent link="base_link" />
        <child link="support" />
        <origin xyz="0 0 ${support_joint_z}" />
    </joint>

    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_raius}" length="${laser_length}" />
            </geometry>
            <material name="laser_color">
                <color rgba="0 0 1 0.8" />
            </material>
        </visual>
    </link>
    <joint name="base2laser" type="fixed">
        <parent link="support" />
        <child link="laser" />
        <origin xyz="0 0 ${laser_joint_z}" />
    </joint>
</robot>